### PR TITLE
feat: add fluent support

### PR DESCRIPTION
**Pull request by sjfhsjfh**
maybe some documentation/examples to be added

### CODE REVIEW

**Comment by jomaway** [comment]
Hi thanks, for the PR. 
Could you please provide some short description about the added changes? 
As you mentioned documentation and examples would also help ;)

**Comment by sjfhsjfh** [comment]
Sorry that I'm not familiar with the CI/Package publish workflow, I found the README.md and example.typ in the repo outdated, so I guess it is up-to-date in the [Universe repo](https://github.com/typst/packages)
I could provide a .typ file to demonstrate the fluent-language usage, but have no idea about how/where to exhibit it

**Comment by jomaway** [comment]
Ah thanks for the hint. I didn't noticed that the readme got out of sync. As there is no fully CI workflow from this repo to publish sometimes small mistakes happens. I will fix this soon. 

you could add your example typ file to the example folder. i need to update my example there as well. 
I need to create some proper docs for this package anyway, but there is a small bug which does not allow linguify to be used in multiple packages, which i need to fix first.

**Comment by sjfhsjfh** [comment]
I'm not sure if it is appropriate to upload a pdf but anyway I added the `.typ` doc, also copied some code that might be useful for documentation😋

**Comment by jomaway** [comment]
Thanks for the documentation. No things got a bit clearer for me. If i try to run my example with your changes i get the following error: 

```
typst compile example/example.typ 
error: dictionary does not contain key "__type"
   ┌─ @preview/linguify:0.3.1/linguify.typ:24:9
   │
24 │   if src.__type == "typst-dict" {
   │          ^^^^^^

help: error occurred in this call of function `get_text`
    ┌─ @preview/linguify:0.3.1/linguify.typ:170:18
    │
170 │       let value = get_text(lang_section, key, default: none, args: args)
    │                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sjfhsjfh** [comment]
That seems weird, it works totally fine for me.
And I'm sure I have checked the `__type` key [here](https://github.com/sjfhsjfh/typst-linguify/blob/main/linguify.typ#L20)
Would you please provide the `.typ` file for some further check?

**Comment by jomaway** [comment]
Yes but the next line was a `if` but needs to be a `else if`. But don't worry I fixed it already. 

Just thinking about your proposed database structure. Wouldn't it be more appropriate to have a tip level key next to `default_lang` for selecting the type. Such as `data_type`. And then we don't need a __type and data key in every language section. 

We then could specify the supported languages directly in this file instead of the document itself to load for ftl_data.

**Comment by sjfhsjfh** [comment]
I guess the v0.4.0 structure would be fine, the L10n implementation should be detached from the linguify i18n structure

**Comment by jomaway** [comment]
I played around with your examples locally, but there are some problem which i encountered:

1. the `ftl_data` uses a read and the path is relative to the `fluent.typ` where the method is located. So it does not work if you don't have access to the package root and give a relative link from there. See [link](https://discord.com/channels/1054443721975922748/1088371919725793360/1222109368305192981) 

2. Suggestion for a `lang.toml` database file, which can be processed.
```toml
[conf]
default-lang = "en"
data_type= "ftl" # dict || ftl

[ftl]
languages = ["en","zh-CN","ja"]

[ftl.args]
name = "Alice & Bob"
date = 2034-01-23
``` 

As of problem 1. the user needs to load the `.ftl` files in his document right now. So i guess it is convenient to add a method which makes it easy to update the database from the read file, which should not be so much a difference to the native approach to read them from the toml file.

**Comment by sjfhsjfh** [comment]
1. *From my aspect* it seems that `linguify` is designed to make i18n "straightfoward", so I guess using the dict should be the default choice(as this is totally enough for simple cases)
2. For fluent args(as Fluent is not "designed" for document L10n, where args are usually static), I suggest keeping it dynamic instead of introducing in the `setup.toml` file or something like that. Similarly, *I think* `linguify` would not only used to do document i18n, but also i18n support for other Typst packages/templates(even translate the assert error message), but I havn't came up with any good idea of maintaining the `args` dict.

~~The [gettext](https://www.gnu.org/software/gettext/manual/html_node/index.html) system maybe a easier one to support though~~

**Comment by sjfhsjfh** [comment]
I'm not quite sure how to deal with the versioning, so maybe we can merge this pr and then work on #2 ? Then for v0.4.0

also for CI convenience should we create the dev branch and setup some branch protection rules😂

**Comment by jomaway** [comment]
> 1. _From my aspect_ it seems that `linguify` is designed to make i18n "straightfoward", so I guess using the dict should be the default choice(as this is totally enough for simple cases)

I agree with you on that one. 

> maybe we can merge this pr and then work on #2 ?

Actually as your current solution is not working in a package due to the ressources constrains of typst, we need to fix this and find some solution until typst has a way of ressource handling, which allows it to wrap a read function. Therefore i would prefer to first update to 0.4.0 and then merge your updated PR based on that. 
I already have a rebased version of your PR locally which i can push, so that you can try to find a valid solution for file loading if used inside a package. 


> also for CI convenience should we create the dev branch and setup some branch protection rules😂

Yeah, as this started as one of too many side projects i haven't done something like this. But if the interest in this grows we should probably do so.

> 2\. For fluent args(as Fluent is not "designed" for document L10n, where args are usually static), I suggest keeping it dynamic instead of introducing in the `setup.toml` file or something like that. Similarly, _I think_ `linguify` would not only used to do document i18n, but also i18n support for other Typst packages/templates(even translate the assert error message), but I havn't came up with any good idea of maintaining the `args` dict.

I see, i have no experience with fluent, even haven't heard of it before you opened this PR. So if you say they should be dynamic it is probably the best way to do so. Still if we add a `[ftl.args]` section to the setup file which is loaded initially we still can change the values dynamically if preferred. This also allows to update this section of the setup file by another tool/program and if you recompile the typst document it will run with updated values. 

Main goal for me is to keep the user API as simple and convenient as possible.

**Comment by sjfhsjfh** [comment]
> Actually as your current solution is not working in a package due to the ressources constrains of typst, we need to fix this and find some solution until typst has a way of ressource handling, which allows it to wrap a read function. Therefore i would prefer to first update to 0.4.0 and then merge your updated PR based on that.

Using `eval` may work, I'd modify the `fluent.typ` later

**Comment by sjfhsjfh** [comment]
I prefer to close this PR and open a new one based on #2 (when finished)

**Pull request closed without merging**
