### PR TITLE
feat: add fluent support

### PR DESCRIPTION
**Pull request by sjfhsjfh**

### CODE REVIEW

**Comment by jomaway** [comment]
Some thoughts about this:

I would prefer if we separate the loading of the fluent data files with the `set_database` function. As that linguify works properly with multiple packages, a package should not use the `set_database` function which uses a global state and instead pass the database directly to the `linguify` function via the `from` parameter. Therefore we should add a function `load_fluent_data` which generates the database from the fluent files and then this can be handled like the dictionary type.

If necessary we can add a type parameter to the conf section, which indicates that this data should be handles differently. 

This leads to my second question. Isn't the only difference from dict to fluent data that fluent values can have arguments in them? Because in the moment it looks like get_message fetches the value for a key which is basically the same as what the typst dict version is doing with the only difference that args are processed. If so we basically can use the current implementation to fetch the value and then pass this result to some other function which processes the the args instead of implementing the same functionality twice.

**Comment by sjfhsjfh** [comment]
> I would prefer if we separate the loading of the fluent data files with the set_database function. 

I added the `ftl_data` function to load fluent files and generate a database dict, see [here](https://github.com/jomaway/typst-linguify/blob/513d1af976c529e7c1065b3acad7f7fea83f8b89/fluent.typ#L27)

> Isn't the only difference from dict to fluent data that fluent values can have arguments in them?

Yes, but `linguify` is a package that could be used in different circumstances, as fluent has a relatively well-developed arguments processing system, so to support it should not contradict the purpose of `linguify`.

> If so we basically can use the current implementation to fetch the value and then pass this result to some other function which processes the the args instead of implementing the same functionality twice.

Actually, in this case, the same functionality(argument processing) is implemented twice, since there's already one implementation(in Rust, and I have compiled it into WASM typst plugin).

Also, the code in this PR does not change the current user's api of `linguify`, litertally only "Adding Fluent Support", so I guess this keeps the i18n *straightforward* and, on top of that, allows users to integrate with the existing workflow(like Fluent).

**Comment by jomaway** [comment]
> Actually, in this case, the same functionality(argument processing) is implemented twice, since there's already one implementation(in Rust, and I have compiled it into WASM typst plugin).

Yes that's what i mean. We use `get_text` to fetch the string from the dictionary and the value which is returned we pass to the WASM plugin for argument processing. Or if someone is keen enough to implement argument processing inside typst we would not need the plugin at all. But that's another thing.

**Comment by sjfhsjfh** [comment]
Currently I'd like to use Fluent + linguify to do i18n for several templates, where compiling a Wasm plugin might be the most feasible solution. So I'm looking forward to v0.4.0 with fluent support🥺

**Comment by jomaway** [comment]
> Currently I'd like to use Fluent + linguify to do i18n for several templates, where compiling a Wasm plugin might be the most feasible solution. So I'm looking forward to v0.4.0 with fluent support🥺

Sure, i think it is a good thing to integrate fluent, but i just want to make sure we get it right and keep it simple and extensible for other i18n solutions.

**Comment by jomaway** [comment]
@sjfhsjfh could you rebase your work or merge the current dev branch into yours, then i can merge your PR.

**Comment by jomaway** [comment]
And would you mind renaming your function `ftl_data` to `load_ftl_data` as then the name is bit more expressive about the functionality

**Comment by sjfhsjfh** [comment]
> @sjfhsjfh could you rebase your work or merge the current dev branch into yours, then i can merge your PR.

> And would you mind renaming your function ftl_data to load_ftl_data as then the name is bit more expressive about the functionality

OK, wait a minute

**Comment by sjfhsjfh** [comment]
Done.

**Comment by sjfhsjfh** [comment]
Oh sorry I modified the `doc/docs.typ` file and switched the import from `preview` to `local`, I'm not sure whether to keep it or not

**Comment by jomaway** [comment]
> Oh sorry I modified the `doc/docs.typ` file and switched the import from `preview` to `local`, I'm not sure whether to keep it or not

I think it should be @preview or importing the file directly. 
You can add a local namespace with preview to test it.

**Comment by jomaway** [comment]
If i run `typst compile fluent-example.typ`  i get the following error.
Bildschirmfoto vom 2024-03-29 13-56-33

**Comment by sjfhsjfh** [comment]
Oh I forgot that😵

**Comment by jomaway** [comment]
Thanks for all your effort, i will do some small cleanup and then publish the new version.

**Pull request merged**
